//! Synthetic video source — generates test patterns without any hardware.
//!
//! Used for:
//! - CI tests (no `vivid` kernel module required)
//! - Dev iteration without a camera
//! - Deterministic regression tests
//!
//! ## Patterns
//!
//! - `SolidColor` — single solid color, useful for sanity checks
//! - `Gradient` — horizontal gradient, useful for visual debugging
//! - `MovingDot` — a single pixel that moves across the frame, useful for
//!   tracker testing (provides a moving target)
//! - `Checkerboard` — classic test pattern

use crate::traits::{VideoResult, VideoSource};
use async_trait::async_trait;
use chrono::Utc;
use common::{Frame, FrameMetadata, PixelFormat};
use std::time::Duration;
use tokio::sync::mpsc;
use tokio::task::JoinHandle;
use tracing::{debug, info};

/// Test pattern generated by `SyntheticVideoSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SyntheticPattern {
    /// Solid color (default: red).
    SolidColor,
    /// Horizontal gradient from black to white.
    #[default]
    Gradient,
    /// A single white pixel that moves across the frame at a configurable speed.
    /// Useful for tracker testing.
    MovingDot,
    /// Classic 8x8 checkerboard.
    Checkerboard,
}

/// Configuration for `SyntheticVideoSource`.
#[derive(Debug, Clone)]
pub struct SyntheticConfig {
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    pub pattern: SyntheticPattern,
    /// If true, the source produces frames forever. If false, it stops after
    /// `max_frames` frames (useful for deterministic tests).
    pub infinite: bool,
    pub max_frames: u64,
}

impl Default for SyntheticConfig {
    fn default() -> Self {
        Self {
            width: 640,
            height: 480,
            fps: 30,
            pattern: SyntheticPattern::Gradient,
            infinite: true,
            max_frames: 0,
        }
    }
}

/// A synthetic video source — generates frames in software, no hardware needed.
pub struct SyntheticVideoSource {
    config: SyntheticConfig,
    capture_task: Option<JoinHandle<()>>,
}

impl SyntheticVideoSource {
    pub fn new(config: SyntheticConfig) -> Self {
        Self {
            config,
            capture_task: None,
        }
    }

    /// Convenience constructor with default config.
    pub fn default_pattern() -> Self {
        Self::new(SyntheticConfig::default())
    }

    /// Render a single frame for the given pattern + sequence number.
    /// Exposed publicly so tests can compare frames deterministically.
    pub fn render_frame(&self, seq: u64) -> Frame {
        let w = self.config.width;
        let h = self.config.height;
        // RGB24 — 3 bytes per pixel
        let mut data = vec![0u8; (w * h * 3) as usize];

        match self.config.pattern {
            SyntheticPattern::SolidColor => {
                // Solid red
                for pixel in data.chunks_exact_mut(3) {
                    pixel[0] = 255; // R
                    pixel[1] = 0; // G
                    pixel[2] = 0; // B
                }
            }
            SyntheticPattern::Gradient => {
                // Horizontal gradient: left=black, right=white
                // Use (w-1) as denominator so the right edge is exactly 255.
                let denom = w.saturating_sub(1).max(1);
                for y in 0..h {
                    for x in 0..w {
                        let val = (x * 255 / denom) as u8;
                        let idx = ((y * w + x) * 3) as usize;
                        data[idx] = val;
                        data[idx + 1] = val;
                        data[idx + 2] = val;
                    }
                }
            }
            SyntheticPattern::MovingDot => {
                // Single white pixel moving horizontally.
                // Position wraps around the frame width.
                let dot_x = (seq % w as u64) as u32;
                let dot_y = h / 2; // middle row
                let idx = ((dot_y * w + dot_x) * 3) as usize;
                if idx + 2 < data.len() {
                    data[idx] = 255;
                    data[idx + 1] = 255;
                    data[idx + 2] = 255;
                }
            }
            SyntheticPattern::Checkerboard => {
                // 8x8 squares
                let square_w = (w / 8).max(1);
                let square_h = (h / 8).max(1);
                for y in 0..h {
                    for x in 0..w {
                        let sq_x = x / square_w;
                        let sq_y = y / square_h;
                        let val = if (sq_x + sq_y) % 2 == 0 { 255 } else { 0 };
                        let idx = ((y * w + x) * 3) as usize;
                        data[idx] = val;
                        data[idx + 1] = val;
                        data[idx + 2] = val;
                    }
                }
            }
        }

        Frame {
            data,
            metadata: FrameMetadata {
                width: w,
                height: h,
                format: PixelFormat::Rgb24,
                captured_at: Utc::now(),
                seq,
            },
        }
    }
}

#[async_trait]
impl VideoSource for SyntheticVideoSource {
    async fn start(&mut self) -> VideoResult<mpsc::Receiver<Frame>> {
        // Channel depth: 1 second of frames (capped to a reasonable max),
        // minimum 3 for burst tolerance. Previously this used max_frames.max(1)
        // which gave bound=1 for infinite sources, severely back-pressuring
        // the producer and cutting throughput.
        let channel_depth = (self.config.fps as usize).clamp(3, 30);
        let (tx, rx) = mpsc::channel(channel_depth);
        let config = self.config.clone();

        info!(
            width = config.width,
            height = config.height,
            fps = config.fps,
            pattern = ?config.pattern,
            channel_depth = channel_depth,
            "starting synthetic video source"
        );

        let handle = tokio::spawn(async move {
            let interval = Duration::from_secs_f64(1.0 / config.fps as f64);
            let mut seq: u64 = 0;

            loop {
                let source = SyntheticVideoSource {
                    config: config.clone(),
                    capture_task: None,
                };
                let frame = source.render_frame(seq);
                debug!(seq = seq, "produced frame");

                // Drop-new policy (same as V4l2Source): if the channel is full,
                // drop the new frame instead of blocking. For real-time video,
                // the freshest frame matters — a backlog of old frames is worse.
                match tx.try_send(frame) {
                    Ok(()) => {}
                    Err(tokio::sync::mpsc::error::TrySendError::Closed(_)) => {
                        debug!("receiver dropped — stopping synthetic source");
                        break;
                    }
                    Err(tokio::sync::mpsc::error::TrySendError::Full(_)) => {
                        debug!("synthetic: channel full, dropping frame {seq}");
                    }
                }

                seq += 1;
                if !config.infinite && seq >= config.max_frames {
                    debug!(
                        seq,
                        max = config.max_frames,
                        "reached max_frames — stopping"
                    );
                    break;
                }
                tokio::time::sleep(interval).await;
            }
        });

        self.capture_task = Some(handle);
        Ok(rx)
    }

    async fn stop(&mut self) -> VideoResult<()> {
        if let Some(handle) = self.capture_task.take() {
            handle.abort();
            debug!("synthetic video source stopped");
        }
        Ok(())
    }

    fn name(&self) -> &str {
        "SyntheticVideoSource"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_gradient_frame_has_correct_size() {
        let source = SyntheticVideoSource::new(SyntheticConfig {
            width: 320,
            height: 240,
            pattern: SyntheticPattern::Gradient,
            ..Default::default()
        });
        let frame = source.render_frame(0);
        assert_eq!(frame.metadata.width, 320);
        assert_eq!(frame.metadata.height, 240);
        assert_eq!(frame.data.len(), 320 * 240 * 3);
        assert_eq!(frame.metadata.format, PixelFormat::Rgb24);
    }

    #[test]
    fn render_solid_color_is_red() {
        let source = SyntheticVideoSource::new(SyntheticConfig {
            width: 4,
            height: 4,
            pattern: SyntheticPattern::SolidColor,
            ..Default::default()
        });
        let frame = source.render_frame(0);
        // First pixel should be red
        assert_eq!(frame.data[0], 255); // R
        assert_eq!(frame.data[1], 0); // G
        assert_eq!(frame.data[2], 0); // B
                                      // Last pixel should also be red
        let last = frame.data.len() - 3;
        assert_eq!(frame.data[last], 255);
    }

    #[test]
    fn render_gradient_has_gradient_values() {
        // With denom = w-1, the right edge (x = w-1) is exactly 255.
        let source = SyntheticVideoSource::new(SyntheticConfig {
            width: 256,
            height: 1,
            pattern: SyntheticPattern::Gradient,
            ..Default::default()
        });
        let frame = source.render_frame(0);
        // Left edge (x=0) should be black
        assert_eq!(frame.data[0], 0);
        // Right edge (x=255): value = 255 * 255 / 255 = 255
        let right_idx = 255 * 3;
        assert_eq!(frame.data[right_idx], 255);
        // Middle (x=128): value = 128 * 255 / 255 = 128
        let mid_idx = 128 * 3;
        assert_eq!(frame.data[mid_idx], 128);
    }

    #[test]
    fn moving_dot_changes_position_per_frame() {
        let source = SyntheticVideoSource::new(SyntheticConfig {
            width: 100,
            height: 10,
            pattern: SyntheticPattern::MovingDot,
            ..Default::default()
        });
        let frame0 = source.render_frame(0);
        let frame1 = source.render_frame(1);
        let frame50 = source.render_frame(50);

        // Moving dot: dot_x = seq % w, dot_y = h/2 = 5
        // Pixel index = (dot_y * w + dot_x) = (5 * 100 + dot_x)
        let find_white = |f: &Frame| -> Option<usize> {
            f.data
                .chunks_exact(3)
                .position(|p| p[0] == 255 && p[1] == 255 && p[2] == 255)
        };

        // Frame 0: dot at x=0, y=5 → pixel index 5*100+0 = 500
        assert_eq!(find_white(&frame0), Some(500));
        // Frame 1: dot at x=1, y=5 → pixel index 5*100+1 = 501
        assert_eq!(find_white(&frame1), Some(501));
        // Frame 50: dot at x=50, y=5 → pixel index 5*100+50 = 550
        assert_eq!(find_white(&frame50), Some(550));
    }

    #[test]
    fn checkerboard_has_alternating_squares() {
        let source = SyntheticVideoSource::new(SyntheticConfig {
            width: 16,
            height: 16,
            pattern: SyntheticPattern::Checkerboard,
            ..Default::default()
        });
        let frame = source.render_frame(0);
        // 8x8 squares → each square is 2x2 pixels
        // Top-left square (0,0) should be white
        assert_eq!(frame.data[0], 255);
        // Top-right square (square_x=7) should be... (7+0)%2=1 → black
        // pixel at x=15, y=0:
        let idx = 15 * 3;
        assert_eq!(frame.data[idx], 0);
    }

    #[tokio::test]
    async fn start_produces_frames() {
        let mut source = SyntheticVideoSource::new(SyntheticConfig {
            width: 64,
            height: 48,
            fps: 100, // fast for tests
            pattern: SyntheticPattern::Gradient,
            infinite: false,
            max_frames: 3,
        });
        let mut rx = source.start().await.unwrap();

        let f0 = rx.recv().await.expect("frame 0");
        let f1 = rx.recv().await.expect("frame 1");
        let f2 = rx.recv().await.expect("frame 2");

        assert_eq!(f0.metadata.seq, 0);
        assert_eq!(f1.metadata.seq, 1);
        assert_eq!(f2.metadata.seq, 2);

        // Channel should be closed after max_frames
        assert!(
            rx.recv().await.is_none(),
            "channel should close after max_frames"
        );

        source.stop().await.unwrap();
    }

    #[tokio::test]
    async fn frames_have_increasing_sequence_numbers() {
        let mut source = SyntheticVideoSource::new(SyntheticConfig {
            width: 32,
            height: 32,
            fps: 200,
            pattern: SyntheticPattern::Gradient,
            infinite: false,
            max_frames: 10,
        });
        let mut rx = source.start().await.unwrap();

        let mut last_seq = None;
        for _ in 0..10 {
            let frame = rx.recv().await.expect("frame");
            if let Some(last) = last_seq {
                assert_eq!(frame.metadata.seq, last + 1, "seq should increment");
            }
            last_seq = Some(frame.metadata.seq);
        }
    }

    #[tokio::test]
    async fn stop_aborts_capture() {
        let mut source = SyntheticVideoSource::new(SyntheticConfig {
            width: 32,
            height: 32,
            fps: 60,
            pattern: SyntheticPattern::Gradient,
            infinite: true,
            max_frames: 0,
        });
        let mut rx = source.start().await.unwrap();
        // Receive a few frames
        for _ in 0..3 {
            let _ = rx.recv().await.expect("frame");
        }
        source.stop().await.unwrap();
        // After stop, channel should close (or already be closing)
        tokio::time::sleep(Duration::from_millis(50)).await;
        // The receiver may still have buffered frames; the key check is that
        // the task is aborted (no new frames produced indefinitely).
    }

    #[test]
    fn default_config_is_reasonable() {
        let cfg = SyntheticConfig::default();
        assert_eq!(cfg.width, 640);
        assert_eq!(cfg.height, 480);
        assert_eq!(cfg.fps, 30);
        assert_eq!(cfg.pattern, SyntheticPattern::Gradient);
        assert!(cfg.infinite);
    }
}
